%{
      title = "Всенощное бдѣніе"
      subtitle = "Nº 1 Приидите, поклонимся"
      composer = "Сергей Рахманинов"
%}

satbLyricsA = \lyricmode {
  А -- минь.
  При -- и -- ди -- те, по -- кло -- ним -- ся Ца -- ре -- ви на -- ше -- му Бо -- гу.
  При -- и -- ди -- те, по -- кло -- ним -- ся и при -- па -- дем Хри -- сту Ца -- ре -- ви на -- ше -- му Бо -- гу.
  При -- и -- ди -- те, по -- кло -- ним -- ся и при -- па -- дем са -- мо -- му Хри -- сту Ца -- ре -- ви и Бо -- гу на -- ше -- му.
  При -- и -- ди -- те, по -- кло -- ним -- ся и при -- па -- дем Е -- му.
}


satbTranslitA = \lyricmode {
  A -- min'.
  Pri -- i -- di -- tye, po -- klo -- nim -- sya Tsa -- re -- vi na -- she -- mu Bo -- gu.
  Pri -- i -- di -- tye, po -- klo -- nim -- sya i pri -- pa -- dyom Khri -- stu Tsa -- re -- vi na -- she -- mu Bo -- gu.
  Pri -- i -- di -- tye, po -- klo -- nim -- sya i pri -- pa -- dyom sa -- mo -- mu Khris -- tu Tsa -- re -- vi i Bo -- gu na -- she -- mu.
  Pri -- i -- di -- tye, po -- klo -- nim -- sya i pri -- pa -- dyom Ye -- mu.
}

