\version "2.22.0"
%{
      title = "Всенощное бдѣніе"
      subtitle = "Nº 2 Благослови, душе моя"
      composer = "Сергей Рахманинов"
%}

sopranoLyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Сла -- ва ти, Гос -- по -- ди, со -- тво -- рив -- ше -- му, со -- тво -- рив -- ше -- му вся.
}

sopranoTranslitB = \lyricmode {
  A -- min'.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Div -- na de -- la Tvo -- ya, Gos -- po -- di.
  Div -- na de -- la Tvo -- ya, Gos -- po -- di.
  Slav -- a ti, Gos -- po -- di, so -- tvo -- riv -- she -- mu, so -- tvo -- riv -- she -- mu vsya.
}

sopranoBLyricsB = \lyricmode {
  Бла -- го -- сло -- вен е -- си,
}

altoLyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Сла -- ва ти, Гос -- по -- ди, со -- тво -- рив -- ше -- му, со -- тво -- рив -- ше -- му вся.
}

altoILyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Сла -- ва ти, Гос -- по -- ди, со -- тво -- рив -- ше -- му, со -- тво -- рив -- ше -- му вся.
}

altoITranslitB = \lyricmode {
  A -- min'.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  Div -- na de -- la Tvo -- ya, Gos -- po -- di.
  Div -- na de -- la Tvo -- ya, Gos -- po -- di.
  Slav -- a ti, Gos -- po -- di, so -- tvo -- riv -- she -- mu, so -- tvo -- riv -- she -- mu vsya.
}

altoIILyricsB = \lyricmode {
  А -- минь.
  _
  _
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  _
  _
  Сла -- ва ти, Гос -- по -- ди, со -- тво -- рив -- ше -- му, со -- тво -- рив -- ше -- му вся.
}

altoIITranslitB = \lyricmode {
  A -- min'.
  _
  _
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  _
  _
  Slav -- a ti, Gos -- po -- di, so -- tvo -- riv -- she -- mu, so -- tvo -- riv -- she -- mu vsya.
}

altoSoloLyricsB = \lyricmode {
  Бла -- го -- сло -- ви, ду -- ше мо -- я, Гос -- по -- да.
  Гос -- по -- ди Бо -- же мой, воз -- ве -- ли -- чил -- ся е -- си зе -- ло.
  Во ис -- по -- ве -- да -- ни -- е и_в ве -- ле -- ле -- по -- ту об -- лекл -- ся е -- си.
  На го -- рах ста -- нут во -- ды.
  По -- сре -- де гор прой -- дут во -- ды.
  Вся пре -- му -- дро -- сти -- ю со -- тво -- рил е -- си, со -- тво -- рил е -- си.
}

altoSoloTranslitB = \lyricmode {
%  Бла -- го -- сло -- ви, ду -- ше мо -- я, Гос -- по -- да.
  Bla -- go -- slo -- vi, du -- she mo -- ya, Gos -- po -- da.
%  Гос -- по -- ди Бо -- же мой, воз -- ве -- ли -- чил -- ся е -- си зе -- ло.
  Gos -- po -- di Bo -- zhe moy, voz -- ve -- li -- chil -- sya ye -- si ze -- lo. 
%  Во ис -- по -- ве -- да -- ни -- е и_в ве -- ле -- ле -- по -- ту об -- лекл -- ся е -- си.
  Vo is -- po -- ve -- da -- ni -- ye i_v ve -- le -- le -- po -- tu ob -- lekl -- sya ye -- si.
%  На го -- рах ста -- нут во -- ды.
  Na go -- rakh sta -- nut vo -- dy.
%  По -- сре -- де гор прой -- дут во -- ды.
  Po -- sre -- de gor proy -- dut vo -- di.
%  Вся пре -- му -- дро -- сти -- ю со -- тво -- рил е -- си, со -- тво -- рил е -- си.
  Vsya pre -- mu -- dro -- sti -- yu so -- tvo -- ril ye -- si, so -- tvo -- ril ye -- si.
}

tenorILyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  _
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  прой -- дут во -- ды.
  _
  Бла -- го -- сло -- ви.
}

tenorITranslitB = \lyricmode {
  A -- min'.
%  Бла -- го -- сло -- ви,
  Bla -- go -- slo -- vi.
%  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
%  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Bla -- go -- slo -- ven ye -- si, Gos -- po -- di.
  _
%  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  Div -- na de -- la Tvo -- ya, Gos -- po -- di.
%  прой -- дут во -- ды.
  proy -- dut vo -- di.
  _
%  Бла -- го -- сло -- ви,
  Bla -- go -- slo -- vi.
}

tenorIILyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
}

tenorIITranslitB = \lyricmode {
  A -- min'.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
}

tenorLyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- ви,
}

tenorALyricsB = \lyricmode {
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  Бла -- го -- сло -- вен е -- си, Гос -- по -- ди.
  _
  Див -- на де -- ла Тво -- я, Гос -- по -- ди.
  прой -- дут во -- ды.
}

tenorBLyricsB = \lyricmode {
  Бла -- го -- сло -- ви,
  Бла -- го -- сло -- ви,
  Бла -- го -- сло -- ви,
  Бла -- го -- сло -- ви,
  Бла -- го -- сло -- ви,
}

bassILyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
}

bassITranslitB = \lyricmode {
  A -- min'.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
}

bassIILyricsB = \lyricmode {
  А -- минь.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  Бла -- го -- сло -- ви.
  со -- тво -- рив -- ше -- му вся. 
}

bassIITranslitB = \lyricmode {
  A -- min'.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  Bla -- go -- slo -- vi.
  so -- tvo -- riv -- she -- mu vsya.
}

