%{
      title = "Всенощное бдѣніе"
      subtitle = "Nº 2 Благослови, душе моя"
      composer = "Сергей Рахманинов"
%}

sopranoMusicB = {
  \dynamicUp
  \autoBeamOff
  \oneVoice
  c'' 2
  c''1\fermata
  R4*33
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'2 |
  a'4. b'8) c''4 d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4 |
  c''1 ~ c''2 r2
  R2*14
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'4 a'4
  a'4. b'8) c''8([ e''8)] d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4
  c''1
  R4*25
  <<{\voiceOne r1 r2 r8 c''8\pp c''8 c''8} \new Voice=VAB {\voiceTwo R2*4}>>
  <<{\voiceOne f''4.( e''8 f''2 e''4. f''8 d''4 c''8[ b'8]} \context Voice=VAB {\voiceTwo c''2 c''4 c''4 c''2( a'4. b'8}>>
  <<{\voiceOne c''4. d''8) e''4 f''4} \context Voice=VAB {\voiceTwo c''4. d''8) e''4 f''4}>> \oneVoice e''4.( c''8 d''4) c''4
  c''1
  R4*32
  c''2\pp c''4 c''4 c''4( a'4 b'4 c''4
  a'4. b'8) c''8([ e''8]) d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4
  c''1
  R2*14
  <<{\voiceOne f''4.( e''8 f''2) e''4 e''8[( f''8)] d''4( c''8[ b'8]} \context Voice=VAC {\voiceTwo c''2( ~ c''4 a'4) c''4 a'4 a'4( f'4 }>>
  <<{\voiceOne c''4. d''8) e''4 f''4 e''4.( c''8 d''4) c''4} \context Voice=VAC {\voiceTwo a'2) a'4 a'8([ b'8)] c''4( a'4 ~ a'8[ g'8]) f'4}>> \oneVoice
  <c'' e'>1
  R2*14
  f''4.(\p e''8 f''2) e''4 e''8([ f''8)] d''4( c''8[ b'8]
  c''4. d''8 e''4 f''4 e''4. c''8 d''4) c''4 
  c''2. c''8\< c''8
  f''4.(\mf e''8 f''2) e''4 e''8([\> f''8)] d''4 c''8([ b')]
  c''4.(\! d''8 e''4 f''4 e''4. c''8) d''4 c''4
  c''\breve^"задерживая" ~
  c''\breve\pp
%  <<{\voiceOne } \context Voice=VAB {\voiceTwo }>>
}

sopranoIMusicB = {
  \dynamicUp
  \autoBeamOff
  \oneVoice
  c''2
  c''1\fermata
  <<{R2*4}{s1^\ritmo_moderato_metà_del_movimento}>>
  R4*25
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'2 |
  a'4. b'8) c''4 d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4 |
  c''1 ~ c''2 r2
  R2*14
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'4 a'4
  a'4. b'8) c''8([ e''8)] d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4
  c''1
  R4*25
  r1 r2 r8 c''8\pp c''8 c''8 |
  f''4.( e''8 f''2 e''4. f''8 d''4 c''8[ b'8] |
  c''4. d''8) e''4 f''4 e''4.( c''8 d''4) c''4 |
  c''1 |
  R4*32
  c''2\pp c''4 c''4 c''4( a'4 b'4 c''4 |
  a'4. b'8) c''8([ e''8]) d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4 |
  c''1
  R2*14
  f''4.( e''8 f''2) e''4 e''8[( f''8)] d''4( c''8[ b'8] |
  c''4. d''8) e''4 f''4 e''4.( c''8 d''4) c''4 |
  c''1
  R2*14
  f''4.(\p e''8 f''2) e''4 e''8([ f''8)] d''4( c''8[ b'8]
  c''4. d''8 e''4 f''4 e''4. c''8 d''4) c''4 
  c''2. c''8\< c''8
  f''4.(\mf e''8 f''2) e''4 e''8([\> f''8)] d''4 c''8([ b')]
  c''4.(\! d''8 e''4 f''4 e''4. c''8) d''4 c''4
  c''\breve^\ritardando ~
  c''\breve\pp
}

sopranoIIMusicB = {
  \dynamicUp
  \autoBeamOff
  \oneVoice
  c'' 2
  c''1\fermata
  R4*33
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'2 |
  a'4. b'8) c''4 d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4 |
  c''1 ~ c''2 r2
  R2*14
  c''2\pp c''4 c''4 c''4( b'8[ a'8] b'4 a'4
  a'4. b'8) c''8([ e''8)] d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4
  c''1
  R4*25
  R2*4
  c''2\pp c''4 c''4 c''2( a'4. b'8 |
  c''4. d''8) e''4 f''4 e''4.( c''8 d''4) c''4 |
  c''1
  R4*32
  c''2\pp c''4 c''4 c''4( a'4 b'4 c''4
  a'4. b'8) c''8([ e''8]) d''4 c''4( b'8[ a'8] b'8[ a'8]) b'4
  c''1
  R2*14
  c''2( ~ c''4 a'4) c''4 a'4 a'4( f'4 |
  a'2) a'4 a'8([ b'8)] c''4( a'4 ~ a'8[ g'8]) f'4 |
  e'1
  R2*14
  f''4.(\p e''8 f''2) e''4 e''8([ f''8)] d''4( c''8[ b'8]
  c''4. d''8 e''4 f''4 e''4. c''8 d''4) c''4 
  c''2. c''8\< c''8
  f''4.(\mf e''8 f''2) e''4 e''8([\> f''8)] d''4 c''8([ b')]
  c''4.(\! d''8 e''4 f''4 e''4. c''8) d''4 c''4
  c''\breve ~
  c''\breve\pp
}

