%{
      title = "Всенощное бдѣніе"
      subtitle = "Nº 5 Ныне отпущаеши"
      composer = "Сергей Рахманинов"
%}

globalMusicE = {
  \override Staff.TimeSignature #'style = #'()
  % 1
  \key bes \minor
  \time 4/4
  \skip 1
  % 2
  \skip 1
  % 3
  \skip 1 %\break
  % 4
  \time 2/4
  \skip 2
  % 5
  \time 4/4
  \skip 1
  % 6
  \skip 1
  % 7
  \skip 1
  % 8
  \skip 1 %\break
  % 9
  \skip 1
  % 10
  \skip 1
  % 11
  \mark \default
  \skip 1
  % 12
  \skip 1 %\break
  % 13
  \skip 1
  % 14
  \skip 1
  % 15
  \skip 1
  % 16
  \time 6/4
  \skip 1. %\break
  % 17
  \skip 1.
  % 18
  \mark \default
  \skip 1.
  % 19
  \skip 1. %\break
  % 20
  \time 4/4
  \skip 1
  % 21
  \time 3/4
  \skip 2.
  % 22
  \time 6/4
  \skip 1. %\break
  % 23
  \time 4/4
  \mark \default
  \skip 1
  % 24
  \skip 1
  % 25
  \skip 1
  % 26
  \skip 1
  % 27
  \skip 1 %\break
  % 28
  \mark \default
  \skip 1
  % 29
  \skip 1
  % 30
  \skip 1
  % 31
  \skip 1
  % 32
  \skip 1 %\break
  % 33
  \skip 1
  % 34
  \time 6/4
  \skip 1.
  % 35
  \skip 1.
  % 36
  \skip 1.
  \bar "|."
  % 37
  \skip 1.
  % 38
  \skip 1.
  \bar "|."
}

topMarksE = {
  s4*139^\lentamente
  s4*18^\perdersi
  s4*12^\short_edition
}

% В автографе отсутствует
% not in the manuscript
% Зтот голос может быть заменен двумя тремя голосами в унисон первых теноров хора
% This part can be sung by two or three voices in unison from among the first tenors in the choir
