%{
      title = "Всенощное бдение"
      subtitle = "Nº 7 Шестопсалмие"
      composer = "Сергей Рахманинов"
%}

bassIMusicG = {
	\dynamicUp
  % 1 0
  R4*26 |
  % 2 10
  |
  % 3 18
  |
  % 4 26
  g2--(^"I" aes2 d2 c2) |
  % 5 34
  bes,1\pp r1 |
  % 6 42
  R4*20 |
  % 7 50
  |
  % 8 62
  r2 g1\p f1 |
  % 9 72
  d2( c2) c2( bes,2) |
  % 10 80
  bes,2 r2 r1 |
  % 11 88
  <f bes,>4--( <aes c>4 <f bes,>4 <aes c>4) <f bes,>4--( <aes c>4 <f bes,>4 <aes c>4) |
  % 12 96
  <f bes,>4--( <aes c>4 <f bes,>4 <aes c>4) <<{<f bes,>4--( <aes c>4 <f bes,>4 <aes c>4}{s2.\< s8\! s8}>> |
  % 13 104
  <<{<f bes,>2 <aes c>2 ~ <aes c>2)\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  ees2--\p\> bes,2\! ees2\pp r4 ees4\< |
  % 15 120
  <<{ees1-- ~ ees4}{s4 s2.\> s4\!}>> ees4\pp ees4 ees4 |
  % 16 128
  ees2.--\> ees4\! ees1 |
  % 17 136
  r2 ees4\pp f4 |
  % 18 140
  g2. aes4 g2(\< f2)\! |
  % 19 148
  c2.\mf\> f4\! c2\p\> ees2\! |
  % 20 156
  ees1\pp ~ ees2\> ees4(\! d4) |
  % 21 164
  ees1\ppp\fermata |
}

bassIIMusicG = {
	\dynamicUp
  % 1 0
  R4*34 |
  % 2 10
  |
  % 3 18
  |
  % 4 26
  |
  % 5 34
  ees,1\pp ~ ees,1 ~ |
  % 6 42
  ees,1 ~ ees,1 |
  % 7 50
  ees,1 ~ ees,1 r1 |
  % 8 62
  r2 bes,2(\p c2) aes,2( bes,2) |
  % 9 72
  g,2( aes,2) f,2( bes,2) |
  % 10 80
  ees,1 ~ ees,1 |
  % 11 88
  ees,1 ees,1 |
  % 12 96
  ees,1 <<{ees,1 ~}{s2.\< s8\! s8}>> |
  % 13 104
  <<{ees,1 ~ ees,2\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  ees2--\p\> bes,2\! ees2\pp r4 aes,4\< |
  % 15 120
  <<{g,1-- ~ g,4}{s4 s2.\> s4\!}>> aes,4\pp bes,4 c8([ bes,8)] |
  % 16 128
  ees2.--\> ees4\! ees1 |
  % 17 136
  r2 ees4\pp f4 |
  % 18 140
  g2. aes4 g2(\< f2)\! |
  % 19 148
  c2.\mf\> f4\! c2\p\> ees2\! |
  % 20 156
  g,1\pp ~ g,2\> aes,2\! |
  % 21 164
  ees,1\ppp\fermata |
}

