\version "2.22.0"
%{
      title = "Всенощное бдение"
      subtitle = "Nº 7 Шестопсалмие"
      composer = "Сергей Рахманинов"
%}

sopranoIMusicG = {
	\dynamicUp
  % 1 0
  R4*34 |
  % 2 10
  |
  % 3 18
  |
  % 4 26
  |
  % 5 34
  r1 ees''2->\p ees''2\pp|
  % 6 42
  R4*8 |
  % 7 50
  bes'2->\p bes'2\pp r1 r1 |
  % 8 62
  R4*18 |
  % 9 72
  |
  % 10 80
  r1 r2 ees''2->(\ppp ~ |
  % 11 88
  ees''8[ d''8 c''8 d''8]) ees''2( ~  ees''8[ d''8 c''8 d''8]) ees''2--( ~ |
  % 12 96
  ees''8[ d''8 c''8 d''8]) ees''8--([ d''8 c''8 d''8]) ees''8--([\< d''8 c''8 d''8]) ees''8--([ d''8 c''8\! d''8] |
  % 13 104
  <<{ees''1 ~ ees''2)\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  g'2--\p\> f'2\! g'2\pp r4 aes'4\< |
  % 15 120
  <<{bes'1-- ~ bes'4}{s4 s2.\> s4\!}>> aes'4\pp g'4 f'8([ g'8)] |
  % 16 128
  aes'2.--\> g'4\! g'1 |
  % 17 136
  r2 g'4\pp aes'4 |
  % 18 140
  bes'2. aes'4 bes'2(\< b'2)\! |
  % 19 148
  c''2.--\mf\> bes'!4\! c''2\p\> g'2 |
  % 20 156
  bes'1\pp ~ bes'2\> aes'2\! |
  % 21 164
  g'1\ppp\fermata |
}


sopranoIIMusicG = {
	\dynamicUp
  % 1 0
  ees'4(\mf f'4 g'4) g'4 g'8([ f'8)] ees'4 f'2-- f'8([ g'8] aes'4) |
  % 2 10
  g'4 g'4 g'8([\> f'8)] ees'4\! f'1-- |
  % 3 18
  g'4\mf g'4 g'4 g'4 g'2\> g'8([\! f'8)]\< ees'4\! |
  % 4 26
  f'2--\> f'4\p f'4 ~ f'4 r4 r2 |
  % 5 34
  r1 c''2->\p c''2\pp |
  % 6 42
  R4*8 |
  % 7 50
  g'2->\p g'2\pp r1 r1|
  % 8 62
  R4*18 |
  % 9 72
  |
  % 10 80
  r1\! r2 c''2->(\ppp ~ |
  % 11 88
  c''8[ bes'8 aes'8 bes'8]) c''2( ~ c''8[ bes'8 aes'8 bes'8]) c''2--( ~ |
  % 12 96
  c''8[ bes'8 aes'8 bes'8]) c''8--[( bes'8 aes'8 bes'8]) c''8--[(\< bes'8 aes'8 bes'8]) c''8--[( bes'8 aes'8\! bes'8] |
  % 13 104
  <<{c''1 ~ c''2)\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  |
  % 15 120
  |
  % 16 128
  |
  % 17 136
  |
  % 18 140
  |
  % 19 148
  |
  % 20 156
  |
  % 21 164
  |
}


sopranoIIIMusicG = {
	\dynamicUp
  % 1 0
  R4*34 |
  % 2 10
  |
  % 3 18
  |
  % 4 26
  |
  % 5 34
  r1 aes'2->\p aes'2\pp |
  % 6 42
  R4*8 |
  % 7 50
  ees'2->\p ees'2\pp r1 r1|
  % 8 62
  ees'4(\pp f'4 g'4) g'4 g'8([ f'8)] ees'4 f'2-- f'8([ g'8] aes'4) |
  % 9 72
  g'4 g'4 g'8([ f'8)] ees'4 f'1--\> |
  % 10 80
  r1\! r2 aes'2->(\ppp ~ |
  % 11 88
  aes'8[ bes'8 c''8 bes'8]) aes'2( ~ aes'8[ bes'8 c''8 bes'8]) aes'2--( ~ |
  % 12 96
  aes'8[ bes'8 c''8 bes'8]) aes'8--[( bes'8 c''8 bes'8]) aes'8--[(\< bes'8 c''8 bes'8]) aes'8--[( bes'8 c''8\! bes'8] |
  % 13 104
  <<{aes'1 ~ aes'2)\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  |
  % 15 120
  |
  % 16 128
  |
  % 17 136
  |
  % 18 140
  |
  % 19 148
  |
  % 20 156
  |
  % 21 164
  |
}

