\version "2.22.0"
humming = \markup {\bold +}
nezhno = \markup { {\dynamic "pp"} "  очень нежно" }

soprano = \markup{ \center-align { "Сопрано" } }
alto = \markup{ \center-align { "Альтъ" } }
tenor = \markup{ \center-align { "Теноръ" } }
bass = \markup{ \center-align { "Басъ" } }

% fairly quick
abbastanza_presto = \markup{\bold "Довольно скоро"}

% In moderate tempo
ritmo_moderato_metà_del_movimento = \markup {\left-align {\bold "Умеренный темп"} "(движение половинами)"}

%
molto_espressivo = \markup { "очень выразительно" }

abbastanza_presto_ma_con_calma_e_delicatezza = \markup {\bold  "Довольно скоро, но покойно и мягко"}
% Ogni volta più forte, più allegro
ogni_volta_più_forte_più_allegro = \markup {\bold  "С каждым разом звучнее, бодрее" }
ritmo_ancora_più_veloce = \markup {\bold  "Темп еще быстрее" }
molto_ritmicamente = \markup {\bold  "очень ритмично" }
senza_sosta_leggero_morbido = \markup {\bold  "Прежний темп  легко мягко" }
senza_sosta = \markup {\bold  "Прежний темп" }

% Piuttosto lentamente ()
piuttosto_lentamente_metà_del_movimento = \markup {{\bold  "Довольно медленно"} "(движение половинами)"}
ritardando_leggermente = \markup {\bold  "немного задерживая"}
% un po 'di evidenziazione
evidenziando_un_po = \markup { \bold "немного выделяя" }
molto_melodioso = \markup {\bold  "очень певуче" }
ritardando = \markup {\bold  "задерживая"}

non_presto = \markup {{\bold  "не скоро"} "(движение половинами)" }
% un po' più lento
un_po_più_lento = \markup { \bold "немного медленнее" }
% tutto è più lento , tutto più debole
tutto_più_lento_più_debole = \markup {\bold  "всё медленнее, всё слабее" }
a_tempo = \markup {\bold  "в темпе" }
% lentamente , molto delicatamente . con un grande senso
lentamente_molto_delicatamente_con_un_grande_senso = \markup {\bold  "медленно, очень мягко. с большим чувством"}


lentamente = \markup {{\bold  "медленно"}}
perdersi = \markup {{\bold "теряясь"}}
short_edition = \markup {{\bold  "Облегченная редакция"}}

%% Part 6
% Andante, leggiero, molto dolce
tempo_Покойно_легко_очень_нежно = \tempo "Покойно, легко, очень нежно"

lunga_pausa = \markup { \column { \center-align {\bold "длинная" \line {\bold "пауза"} } } }

% In the original manuscript titled Doxology small
% = \markup { "В автографе первоначально озаглавлено Славословие малое" }

% non presto
tempo_не_скоро = \tempo "не скоро"
% ritardando
tempo_задерживая = \tempo "задерживая"

% dolce, cantabile
dir_мягко_певуче = \markup {\small "мягко, певуче"}

% carattere come sopra
dir_Прежний_характер = \markup {\small "Прежний характер"}

% melodioso
dir_певуче = \markup {\small "певуче"}

% Bright, with a strong, solid rhthym
dir_ярко_с_твербым_добрым_рутмом = \markup { \small "ярко, с твербым, добрым рутмом"}
