\version "2.22.0"
%{
      title = "Всенощное бдѣніе"
      subtitle = "Nº 7 Шестопсалмие"
      composer = "Сергей Рахманинов"
%}

satbLyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

satbLyricsG = \lyricmode {
	ˈslɑ -- va v~ˈvɨʃ -- nʲix ˈbo -- gu
	i nɑ zʲɛm -- ˈlʲi mʲir
	v~tʃɛ -- lo -- ˈvʲɛ -- tsɛx bla -- go -- vo -- ˈlʲe -- nʲi -- jɛ
	ˈgos -- po -- dʲi ust -- ˈnʲɛ mo -- ˈi ot -- ˈvʲɛr -- zʲɛ -- ʃɨ
	i u -- ˈstɑ mo -- ˈja voz -- vʲɛ -- ˈstʲat xva -- ˈlu tvo -- ˈju
}

sopranoILyricsG = \lyricmode {
  Сла -- ва,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

sopranoIILyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
  Сла -- ва,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

sopranoIIILyricsG = \lyricmode {
  Сла -- ва,
  Сла -- ва,
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
%	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
  Сла -- ва,
  Сла -- ва,
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

altoILyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

altoIILyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
	в_че -- ло -- ве -- цех бла -- го -- во -- ле -- ни -- е.
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

tenorILyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
  Сла -- ва,
  Сла -- ва.
	Сла -- ва в_выш -- них Бо -- гу,
	и на зем -- ли мир,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва.

	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

tenorIILyricsG = \lyricmode {
	Сла -- ва в_выш -- них Бо -- гу,
  Сла -- ва,
  Сла -- ва.
	и на зем -- ли мир,
  Сла -- ва,
  Сла -- ва,
  Сла -- ва.
}

bassILyricsG = \lyricmode {
	Сла -- ва, 
	и на зем -- ли мир,
  Сла -- ва,
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

bassIILyricsG = \lyricmode {
	Сла -- ва, 
	и на зем -- ли мир,
  Сла -- ва,
  Сла -- ва.
	Гос -- по -- ди, уст -- не мо -- и от -- вер -- зе -- ши,
	и у -- ста мо -- я воз -- ве -- стят хва -- лу Тво -- ю.
}

sopranoITranslitG = \lyricmode {
Sla -- va,
Sla -- va,
Sla -- va,
Sla -- va,
Sla -- va.
Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

sopranoIITranslitG = \lyricmode {
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va,
Sla -- va.
Sla -- va,
Sla -- va,
Sla -- va.
Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

sopranoIIITranslitG = \lyricmode {
Sla -- va,
Sla -- va.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
%v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va,
Sla -- va,
Sla -- va.
Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

altoITranslitG = \lyricmode {
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.

Sla -- va.
Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

altoIITranslitG = \lyricmode {
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
v_che -- lo -- ve -- tsekh bla -- go -- vo -- le -- ni -- ye.

Sla -- va.
Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

tenorITranslitG = \lyricmode {
Sla -- va v_vysh -- nikh Bo -- gu,
Sla -- va,
Sla -- va.
Sla -- va v_vysh -- nikh Bo -- gu, i na zem -- li mir,
Sla -- va,
Sla -- va,
Sla -- va.

Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

tenorIITranslitG = \lyricmode {
Sla -- va v_vysh -- nikh Bo -- gu,
Sla -- va,
Sla -- va.
i na zem -- li mir,
Sla -- va,
Sla -- va,
Sla -- va.

Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

bassITranslitG = \lyricmode {
Sla -- va, i na zem -- li mir,
Sla -- va,
Sla -- va.

Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}

bassIITranslitG = \lyricmode {
Sla -- va, i na zem -- li mir,
Sla -- va,
Sla -- va.

Gos -- po -- di, ust -- ne mo -- i ot -- ver -- ze -- shi,
i u -- sta mo -- ya voz -- ve -- styat khva -- lu Tvo -- yu.
}



