\version "2.22.0"
%{
      title = "Всенощное бдение"
      subtitle = "Nº 7 Шестопсалмие"
      composer = "Сергей Рахманинов"
%}

tenorIMusicG = {
	  % 1 0
  ees'2(\p d'2 <<{c'2)}{s4 s4\>}>> d'2--(\! ees'2) |
  % 2 10
  d'2--( <<{c'2)}{s4 s4\>}>> d'2--(\! ees'2) |
  % 3 18
  d'2( c'2 d'2 ees'2) |
  % 4 26
  d'2--(\pp c'2 bes2 aes2 |
  % 5 34
  g1) r1 |
  % 6 42
  g'1->(\pp f'1) |
  % 7 50
  ees'4 r4 r2 d'1->\pp c'2( d'2) |
  % 8 62
  ees'4(\pp f'4 g'4) g'4 g'8([ f'8)] ees'4 f'2-- f'8([ g'8] aes'4) |
  % 9 72
  g'4 g'4 g'8([ f'8)] ees'4 f'1 |
  % 10 80
  r2 <g' ees'>1.\ppp |
  % 11 88
  <f' ees'>2 <f' ees'>1-- <f' ees'>2 ~ |
  % 12 96
  <f' ees'>2 <<{<f' ees'>1-- <f' ees'>2 ~}{s2 s2.\< s8\! s8}>> |
  % 13 104
  <<{<f' ees'>1 ~ <f' ees'>2\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  bes2--\p\> bes2\! bes2\pp r4 c'4\< |
  % 15 120
  <<{des'1-- ~ des'4}{s4 s2.\> s4\!}>> c'4\pp bes4 aes8([ bes8)] |
  % 16 128
  c'2.--\> bes4\! bes1 |
  % 17 136
  r2 bes4\pp bes4 |
  % 18 140
  bes2. bes4 bes2(\< aes2)\! |
  % 19 148
  g2.--\mf\> aes4\! g2\p\> d'2\! |
  % 20 156
  des'1\pp ~ des'2\> c'2\! |
  % 21 164
  bes1\ppp\fermata |
}

tenorIIMusicG = {
	  % 1 0
  c'2(\p g2 <<{aes2)}{s4 s4\>}>> bes2--(\! c'2) |
  % 2 10
  g2--( <<{aes2)}{s4 s4\>}>> bes2--(\! c'2) |
  % 3 18
  g2( aes2 bes2 c2) |
  % 4 26
  d'4 r4 r2 r1|
  % 5 34
  R4*8 |
  % 6 42
  <ees' c'>1->(\pp ~ <ees' c'>2 bes2) |
  % 7 50
  ees'4 r4 r2 <bes g>1->\pp aes2( bes2) |
  % 8 62
  c'2(\p d'2 ees'2) c'2( d'2) |
  % 9 72
  bes2( c'2) aes1 |
  % 10 80
  g2 c'1.->\ppp |
  % 11 88
  c'2 c'1 c'2-> ~ |
  % 12 96
  c'2 <<{c'1-> c'2-> ~}{s2 s2.\< s8\! s8}>> |
  % 13 104
  <<{c'1 ~ c'2\fermata}{s2\< s2\f\> s2\!}>> r2\fermata |
  % 14 112
  |
  % 15 120
  |
  % 16 128
  |
  % 17 136
  |
  % 18 140
  |
  % 19 148
  |
  % 20 156
  |
  % 21 164
  |
}

